[project]
name = "StockUtils"
version = "0.0.1"
authors = [
    {name = "John Doe", email = "john@doe.com"},
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"

[tool.setuptools]
py-modules = []